# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  PYTEST_RUN_PATH: $GITHUB_WORKSPACE\..\tests
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        poetry-version: [1.3.2]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
          
      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
            
      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'
        
      - name: Activate env and Test with pytest
        env:
          PYTEST_PLUGINS: pytest_github_actions_annotate_failures
        run: poetry run pytest


  # linter:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: ["3.10", "3.11"]
  #       os: [ubuntu-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install project
  #       run: make install
  #     - name: Run linter
  #       run: make lint

  # tests_linux:
  #   needs: linter
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: ["3.10", "3.11"]
  #       os: [ubuntu-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install project
  #       run: make install
  #     - name: Run tests
  #       run: make test
  #     - name: "Upload coverage to Codecov"
  #       uses: codecov/codecov-action@v3
        # with:
        #   fail_ci_if_error: true

  # tests_mac:
  #   needs: linter
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: ["3.10", "3.11"]
  #       os: [macos-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install project
  #       run: make install
  #     - name: Run tests
  #       run: make test

  # tests_win:
  #   needs: linter
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: ["3.10", "3.11"]
  #       os: [windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install Pip
  #       run: pip install --user --upgrade pip
  #     - name: Install project
  #       run: pip install -e .[test]
  #     - name: run tests
  #       run: pytest -s -vvvv -l --tb=long tests
